language: generic
sudo: false
dist: trusty

cache:
  apt: true
  directories:
    - $HOME/usr/
    - $HOME/.sonar/cache
    - build/resources

matrix:
  include:
    - stage: build
      os: windows
      language: shell
      script: powershell .ci/setup_appveyor.ps1
