os: windows
language: shell

cache:
  directories:
    - build/resources

matrix:
  include:
    - stage: dependencies
      script: TASK=dependencies .ci/setup_appveyor.bat
    - stage: build
      script: .ci/setup_appveyor.bat
